### ISSUE TITLE
Improve Indications for Tower Placeholder

### ISSUE THREAD

**Issue by marvinbuff** [marvinbuff/GalacticCombat#11]
### Description
The tower placeholder should have improved UI.

### To-Do
- [x] Show final tower range
- [x] Add rules to prevent tower placement on path, other towers, or obstacles.
- [x] Indicate more clearly when hovering over illegal positions
