### ISSUE TITLE
Level Editor Window

### ISSUE THREAD

**Issue by marvinbuff** [marvinbuff/GalacticCombat#14]
## To-Do
- [ ] Add isEditable variable to LevelData
- [ ] Add switches on isEditable for:
  - [ ] Creating/Removing path vertices
  - [ ] Drag'n'dropping path vertices
  - [ ] Drag'n'dropping slider items
  - [ ] Opening Level Editor Window
- [ ] Design Level Editor Window
- [ ] ...
