### ISSUE TITLE
Create Level 1

### ISSUE THREAD

**Issue by marvinbuff** [marvinbuff/GalacticCombat#15]
## To-Do
- [x] Design Level 1 Path
- [x] Adjust Invader and Tower statistics to be reasonable
- [x] Design Level 1 Waves
- [x] Finish playable level
