### ISSUE TITLE
Support multiple invader paths

### ISSUE THREAD

**Issue by marvinbuff** [marvinbuff/GalacticCombat#16]
Enable the usage of multiple paths as suggested by the LevelData already in place.

### To-Do
- [ ] Enable drawing of multiple paths
- [ ] Spawn invaders on the correct path
- [ ] Adjust editor and developer tools
