### ISSUE TITLE
Implement Tower Upgrading System

### ISSUE THREAD

**Issue by marvinbuff** [marvinbuff/GalacticCombat#20]
Towers are currently stuck at level 1. In the future, it should be possible to upgrade them using experience. Upgrading a tower changes its statistics and look. 

### To-Do
- [x] Read in config data holding all tower data information 
  - [x] Design config Json ("sporeLauncher" -> { damage:3 })
  - [x] Create default configuration
  - [x] Override default configuration with mod-folder
- [x] Use tower data configuration to create towers
- [x] Create function to upgrade towers which updates views and behaviour
- [x] Add upgrading button in info panel

**Comment by marvinbuff** [comment]
Done.
