### ISSUE TITLE
Implement Tower Specializations

### ISSUE THREAD

**Issue by marvinbuff** [marvinbuff/GalacticCombat#22]
Towers are currently only leveling up from 1 to 5 in a linear manner. We also want to support specializations for level 4 and 5.

### To-Do
- [ ] Adjust tower configs to encode variants for level 4 and 5
- [ ] Design and setup configuration for those variants
- [ ] Add UI to choose specialization
