### ISSUE TITLE
Migrate notes file to wiki

### ISSUE THREAD

**Issue by marvinbuff** [marvinbuff/GalacticCombat#24]
### To-Do
- [ ] Design wiki layout
- [ ] Migrate notes information to new wiki
- [ ] Fill gaps and create follow up tickets to complete wiki
