### ISSUE TITLE
Re-enable the game menu

### ISSUE THREAD

**Issue by marvinbuff** [marvinbuff/GalacticCombat#26]
Activate the game menu and implement basic usage.

### To-Do
- [ ] Reactivate game menu
- [ ] Define use cases and test their functionality
- [ ] Fix the unresponsive layer after restarting a game
