### ISSUE TITLE
Level Spawn Slider

### ISSUE THREAD

**Issue by marvinbuff** [marvinbuff/GalacticCombat#6]
### To-Do
- [x] Add container to fxml
- [x] Create slider object from timer controller
- [x] Build slider UI
  - [x] Add button to forward to next level
  - [x] The slider
  - [x] Visual indication of the invaders
  - [x] Visual indication of passing time
- [x] Enable drag'n'drop for invaders (should modify underlying level file)
- [x] Store level using shortcut
